# Generated by Django 5.2.16 on 2026-07-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='target_date',
        ),
    ]
